services:
  - type: web
    name: trading-bot-webhook
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn webhook_listener:app"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "8090436532:AAEdtagv5svIKQOT0JG1Te6aFsRwjk3rXVA"
      - key: TELEGRAM_CHAT_ID
        value: "8098105128"
